# shortsync config
#
# shortcuts: Source the shortcut files, default format is
#            any plain text file comment syntax is a #.
#     alias-shortcuts: Source the alias shortcut file.
#     file-shortcuts: Source the file shortcut file.
#     folder-shortcuts: Source the folder shortcut file.

# anyapplication: You can put any name you would like, this is used
#                 to load the config of a specific application.
#   configpath: This designates where the source command is to be appended.
#   sourcecmd: This is the format of the source command keywords are $path$.
#   outputpath: Where would you like to store the shortcut file.
#   outputformat: What format would you like the shortcut file in,
#                 keywords are $aliases$, $files$, $folders$ each
#                 keywords relates to which shortcut file to output.
#   aliasformat: What format makes an alias to a command,
#                keywords are $short$, $cmd$.
#   filesformat: What format makes an alias to open a specific file,
#                keywords are $short$, $path$.
#   foldersformat: What format makes an alias to navigate to a specific folder,
#                  keywords are $short$, $path$.

shortcuts:
    alias-shortcuts: "$HOME/.config/shortsync-example/shortcut-configs/alias_shortcuts.conf"
    file-shortcuts: "$HOME/.config/shortsync-example/shortcut-configs/file_shortcuts.conf"
    folder-shortcuts: "$HOME/.config/shortsync-example/shortcut-configs/folder_shortcuts.conf"

bash:
    configpath: "~/.bashrc"
    sourcecmd: "source $path$"
    outputpath: "$HOME/.config/shortsync/shortcut-files/bash_shortcuts"
    outputformat: "# alias shortcuts\n$aliases$\n# file shortcuts\n$files$\n# folder shortcuts\n$folders$\n"
    aliasformat: "alias $short$=\"$cmd$\""
    filesformat: "alias $short$=\"$EDITOR $path$\""
    foldersformat: "alias $short$=\"cd $path$\""
